CREATE DEFINER = CURRENT_USER TRIGGER `hana`.`idroom_creation` BEFORE INSERT ON `room` FOR EACH ROW
BEGIN
SET NEW.idROOM = concat('ROOM', LPAD(COALESCE((SELECT MAX(CAST(SUBSTRING(idROOM,4,3) AS UNSIGNED))+ 1 FROM room), 1), 4, '0'));
END